name: garage
description: "workflow management project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0
  flutter_svg: ^2.0.17
  json_annotation: ^4.9.0
  intl: ^0.20.2
  timelines_plus: ^1.0.6
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  firebase_analytics: ^10.8.10

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_gen_runner: ^5.10.0
  mobx_codegen: ^2.7.0
  json_serializable: ^6.9.5

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
dependency_overrides:
  source_gen: ^2.0.0
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/


flutter_gen:
  output: lib/gen/ # or whatever path you prefer

  assets:
    enabled: true

  integrations:
    flutter_svg: true # only if using flutter_svg
